name: uiam_personal
version: 1.0.0+1
publish_to: none
description: Universal Identity and Appointment Management System.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  firebase_auth: ^3.3.18
  flutterfire_ui: ^0.4.1
  simple_animations: 4.0.2
  flutter: 
    sdk: flutter
  geoflutterfire: ^3.0.3
  device_preview: ^1.1.0
  date_time_picker: ^2.1.0
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  path: ^1.8.1
  freezed_annotation: ^2.0.3
  octo_image: ^1.0.2
  cached_network_image: ^3.2.1
  dropdown_search: ^5.0.2
  geolocator: ^8.2.1
  intl: ^0.17.0
  table_calendar: ^3.0.6
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.0.0
  http: ^0.13.4
  web3dart: ^2.3.5
  web_socket_channel: ^2.2.0
  crypto: ^3.0.2

dev_dependencies: 
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter: 
  uses-material-design: true
  assets:
    - src/abis/UiamContract.json

